name: rui_pedro_s_application11
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  shared_preferences: ^2.0.18
  http: ^1.2.2
  flutter:
    sdk: flutter
  sqflite: ^2.3.3+1
  dio: ^5.0.0
  path: ^1.8.2  # Atualize para a versão mais recente disponível
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  carousel_slider: ^5.0.0
  file_picker: ^5.2.1
  smooth_page_indicator: ^1.1.0
  calendar_date_picker2: ^1.1.5
  syncfusion_flutter_pdf: ^23.2.7
  path_provider: ^2.0.7
  open_file: ^3.2.1
  intl: ^0.18.1
  image_picker: ^0.8.7+4 # Adiciona a dependência image_picker
  permission_handler: ^10.2.0 # Adiciona a dependência permission_handler
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/NunitoBold.ttf
          weight: 700
        - asset: assets/fonts/NunitoRegular.ttf
          weight: 400
        - asset: assets/fonts/NunitoMedium.ttf
          weight: 500
        - asset: assets/fonts/NunitoExtraBold.ttf
          weight: 800
    - family: Inter
      fonts:
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
        - asset: assets/fonts/InterSemiBold.ttf
          weight: 600
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
        - asset: assets/fonts/InterBold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/RobotoRegular.ttf
          weight: 400
        - asset: assets/fonts/RobotoBold.ttf
          weight: 700
        - asset: assets/fonts/RobotoMedium.ttf
          weight: 500
